spring.application.name=intershop
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/intershop
spring.datasource.username=intershop
spring.datasource.password=intershop

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=debug